[gsheets]
type = "service_account"
project_id = "streamlit-data-monev"
private_key_id = ""
private_key = """-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----"""
client_email = ""
client_id = "101285445995782838941"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-monev-testing%40streamlit-data-monev.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[general]
gsheet_id = "13VX7U0GVooDCfs7XVJsY_-_vn3nLMpPE2as_SSkiPS0"
