[general]
gsheet_id = "13VX7U0GVooDCfs7XVJsY_-_vn3nLMpPE2as_SSkiPS0"

[gsheets]
type = "service_account"
project_id = "streamlit-data-monev"
private_key_id = "4c98f68a34e6e32813a7f480fb9ecbfd73a2374e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQD2Rt+5KHi//x0+
e0FbGDeJDAPPqc4nHBqr7Uwnsi8GqLklZTjLUmoHu7g3mCiA/9QKgwsKxJcEXHGH
NLf75xujNKHVYdkSLz7hXlQfNIkAIWWq6bKT4V+QdGRS1tl8nSylBhh8lu989Rk6
MZLMp9fufZDUUUF2dlGcLHSqK5GcFKMtGOAOrb+XScz0Yj3xriEMrzr13d79Yp+o
hqW41eACRI4QnZ3EBodxVf6hlGU96EzQiyDQfxciKEP8Yc6GEajgi9oxE+qLs5uO
4M0TnuM0a+juTFHrGFnN/s2YddjUwURdEEhpA+eiCJyVBRlmFhRnW37WnkrsVIPL
E2RyQKwzAgMBAAECggEAdI/t8rprkF/kTP7UW5O2MUi9Aww5FPyxyP7q5PzqUgoI
e2ERxPXwVlGsaq+7N/cduo30a3fJjFheqWIz1Ge5hoDyOcbykS9IYS2evhhE4Ylt
D7xFd8WbUAkutKCY1mijyUV90HY1ypxNAOSWuQOV6XyH0F3XEIUGsla+Lw6o/8g9
FRflLLetMAvjCW2h6tG1PuKkSPTeI/W9cgSZNSz3TyKtyAmwqXpHZ6iBMRM023Jm
AX3JbZvU8P+hKbBKAG+FISFYOHJvHYSEpetEco5ifAvMxkGf/9mGuBJ1f+fYF8yW
yUFHdwI9/YzgXu7Lyuu+mKLKSBLMwBEZgG4HkbDseQKBgQD8M7c0plSAfGcHz1A/
3Bky7jMR2mQZnP+1mwROoq5j+NeaxQKjxzmYZajhSM1DrXgic7K2fzA3Vp8EUZwN
WaXYn4TPtoTqPt5OJriQ+giRSBhoZEXKrgHIa16BEBOAwGg+9uWEfUdZBwsUGUPJ
FqsByGV0asBDvMTxnx+aRIzGSwKBgQD5/FDRjX0tZWUBAq6jbIkqLjdm+vUAf9HH
i1T+3dEeopy5b1Zrj8sl3ynmMtsDc4zQAQwjbZoSf+ddvSggVaD/BfffdgKFFMbb
pnX30rxBVssf5PnWQzyNazdZ+FCEbTIGOLh5WfJ/5EzK9bwy87eiAgIJjk+kac7/
+r4hybQguQKBgQD3FHtyW1oCHt6ZqiOGzMzrNq5V2U2kQknK07oeiAat7sbb3BM/
/RiSE1amj7p5iWNe7VaysFy+emCDzKhD9AYk+fMVxEznaPxGOG0tq6flHWq8KzCs
5ljcz0Pg0a0pwFbhCOXHLS1PLTVPVYkxYsHal0e+DC+crT2NMkW1z17TjQKBgQDK
RlyKwybnpaStxaLTv43ZYJ4ZqLS4G7T99oLm20tLs56G+Uz/KdHiKgn4J2xKBaSJ
5l8RB61kjLQEiHtAdqkX0Zd47D8rud0SfEX2KkGDyRwBCcESm0MS1w9psGBOVyDk
Id866gora+qrS11mCQisgV1uqAVPbwI85IIWSuSCmQKBgQD0HqXU3FRYNASK+70z
REMHeg+wbVLsFMkI/PvZIpS89e+1pufFucCak+ShNX7tj4gy4Vy5KIvodPZfAvV0
6uxK2f8xcLaOTK6OIuh1NAaFPQLuqlkKS0T4q83HUamgnGpfBAGJqY+ntWAPbGu6
GC3I2Qyp/cmsiaHCilmz1NZCDg==
-----END PRIVATE KEY-----"""

client_email = "streamlit-monev-testing@streamlit-data-monev.iam.gserviceaccount.com"
client_id = "101285445995782838941"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-monev-testing%40streamlit-data-monev.iam.gserviceaccount.com"
universe_domain = "googleapis.com"